=== fchavonet/full_stack-db_visual_adventure_cards_api/schema/card.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/fchavonet/full_stack-db_visual_adventure_cards_api/schema/card.schema.json",
  "title": "Visual Adventure Card",
  "type": "object",
  "required": [
    "id",
    "part",
    "number",
    "title_jp",
    "rarity",
    "front_image_url",
    "back_image_url",
    "updated_at"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^p[\\w]+-\\d{3}[a-z]?$"
    },
    "part": {
      "type": "string",
      "minLength": 1
    },
    "number": {
      "type": "string",
      "pattern": "^\\d{3}$"
    },
    "year": {
      "type": "integer",
      "minimum": 1900
    },
    "title_jp": {
      "type": "string",
      "minLength": 1
    },
    "title_en": {
      "type": "string"
    },
    "title_fr": {
      "type": "string"
    },
    "rarity": {
      "type": "string",
      "enum": [
        "standard",
        "prism",
        "special"
      ]
    },
    "front_image_url": {
      "type": "string",
      "format": "uri"
    },
    "back_image_url": {
      "type": "string",
      "format": "uri"
    },
    "prism_mask_url": {
      "type": "string",
      "format": "uri"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    }
  },
  "additionalProperties": false
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-066.json
{
  "id": "p2-066",
  "part": "2",
  "number": "066",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "悟空大活劇！",
  "title_en": "Goku's Great Adventure!",
  "title_fr": "La grande aventure de Goku !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2/part_2-066.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2/part_2-066.webp",
  "updated_at": "2026-08-25T13:11:54.260Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-026.json
{
  "id": "p1-026",
  "part": "1",
  "number": "026",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "いってきま～す！",
  "title_en": "I’m leaving!",
  "title_fr": "J’y vais !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_1-026.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_1-026.webp",
  "updated_at": "2026-08-17T17:05:29.386Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-038.json
{
  "id": "p1-038",
  "part": "1",
  "number": "038",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "ここはナメック星",
  "title_en": "This is Planet Namek",
  "title_fr": "Ici, c’est la planète Namek",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_1/part_1-038.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_1/part_1-038.webp",
  "updated_at": "2026-08-25T10:29:06.860Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-047.json
{
  "id": "p2-047",
  "part": "2",
  "number": "047",
  "year": 1991,
  "rarity": "prism",
  "title_jp": "天下分け目の超決戦！",
  "title_en": "The ultimate decisive battle!",
  "title_fr": "Le combat décisif ultime !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards-api/assets/images/front/part_2/part_2-047.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards-api/assets/images/back/part_2/part_2-047.webp",
  "prism_mask_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards-api/assets/images/mask/part_2/part_2-047.webp",
  "updated_at": "2026-08-25T19:05:07.879Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p3-111.json
{
  "id": "p3-111",
  "part": "3",
  "number": "111",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "1対1の勝負！",
  "title_en": "A one-on-one showdown!",
  "title_fr": "Un duel en un contre un !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_3/part_3-111.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_3/part_3-111.webp",
  "updated_at": "2026-08-25T11:47:40.838Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-078.json
{
  "id": "p2-078",
  "part": "2",
  "number": "078",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "ザーボンの怒り",
  "title_en": "Zarbon's anger",
  "title_fr": "La colère de Zarbon",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2-078.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2-078.webp",
  "updated_at": "2026-08-17T17:05:29.402Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-035.json
{
  "id": "p1-035",
  "part": "1",
  "number": "035",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "激闘開始",
  "title_en": "The fierce battle begins",
  "title_fr": "Le combat acharné commence",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_1/part_1-035.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_1/part_1-035.webp",
  "updated_at": "2026-08-25T11:47:40.819Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-034.json
{
  "id": "p1-034",
  "part": "1",
  "number": "034",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "ちょっとひとやすみ",
  "title_en": "Let’s take a short rest",
  "title_fr": "On fait une petite pause",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards-api/assets/images/front/part_1/part_1-034.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards-api/assets/images/back/part_1/part_1-034.webp",
  "updated_at": "2026-08-25T19:05:07.873Z"
}
