=== fchavonet/full_stack-db_visual_adventure_cards_api/schema/card.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/fchavonet/full_stack-db_visual_adventure_cards_api/schema/card.schema.json",
  "title": "Visual Adventure Card",
  "type": "object",
  "required": [
    "id",
    "part",
    "number",
    "title_jp",
    "rarity",
    "front_image_url",
    "back_image_url",
    "updated_at"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^p[\\w]+-\\d{3}[a-z]?$"
    },
    "part": {
      "type": "string",
      "minLength": 1
    },
    "number": {
      "type": "string",
      "pattern": "^\\d{3}$"
    },
    "year": {
      "type": "integer",
      "minimum": 1900
    },
    "title_jp": {
      "type": "string",
      "minLength": 1
    },
    "title_en": {
      "type": "string"
    },
    "title_fr": {
      "type": "string"
    },
    "rarity": {
      "type": "string",
      "enum": [
        "standard",
        "prism",
        "special"
      ]
    },
    "front_image_url": {
      "type": "string",
      "format": "uri"
    },
    "back_image_url": {
      "type": "string",
      "format": "uri"
    },
    "prism_mask_url": {
      "type": "string",
      "format": "uri"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    }
  },
  "additionalProperties": false
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p3-119.json
{
  "id": "p3-119",
  "part": "3",
  "number": "119",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "ザーボンVSベジータ",
  "title_en": "Zarbon VS Vegeta",
  "title_fr": "Zarbon contre Vegeta",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_3/part_3-119.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_3/part_3-119.webp",
  "updated_at": "2026-08-25T11:47:40.838Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-029.json
{
  "id": "p1-029",
  "part": "1",
  "number": "029",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "到着",
  "title_en": "Arrival",
  "title_fr": "Arrivée",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_1-029.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_1-029.webp",
  "updated_at": "2026-08-17T17:05:29.387Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-051.json
{
  "id": "p2-051",
  "part": "2",
  "number": "051",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "かかってこいや！",
  "title_en": "Bring it on!",
  "title_fr": "Viens te battre !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2/part_2-051.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2/part_2-051.webp",
  "updated_at": "2026-08-25T13:11:54.255Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-068.json
{
  "id": "p2-068",
  "part": "2",
  "number": "068",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "つかまってろよ！",
  "title_en": "Hang on!",
  "title_fr": "Accroche-toi !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2/part_2-068.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2/part_2-068.webp",
  "updated_at": "2026-08-25T13:11:54.260Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-071.json
{
  "id": "p2-071",
  "part": "2",
  "number": "071",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "パワーアップ！",
  "title_en": "Power up!",
  "title_fr": "Puissance maximale !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2/part_2-071.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2/part_2-071.webp",
  "updated_at": "2026-08-25T09:35:44.858Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-053.json
{
  "id": "p2-053",
  "part": "2",
  "number": "053",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "射てーっ！",
  "title_en": "Fire!",
  "title_fr": "Feu !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2/part_2-053.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2/part_2-053.webp",
  "updated_at": "2026-08-25T11:47:40.824Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p3-122.json
{
  "id": "p3-122",
  "part": "3",
  "number": "122",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "最長老の危機！",
  "title_en": "The Grand Elder in danger!",
  "title_fr": "Le Grand Ancêtre en danger !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_3-122.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_3-122.webp",
  "updated_at": "2026-08-23T11:51:44.055Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p3-103.json
{
  "id": "p3-103",
  "part": "3",
  "number": "103",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "ピラフ一味の挑戦",
  "title_en": "The Pilaf Gang's challenge",
  "title_fr": "Le défi de la bande de Pilaf",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards-api/assets/images/front/part_3/part_3-103.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards-api/assets/images/back/part_3/part_3-103.webp",
  "updated_at": "2026-08-25T19:05:07.898Z"
}
