=== fchavonet/full_stack-db_visual_adventure_cards_api/schema/card.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/fchavonet/full_stack-db_visual_adventure_cards_api/schema/card.schema.json",
  "title": "Visual Adventure Card",
  "type": "object",
  "required": [
    "id",
    "part",
    "number",
    "title_jp",
    "rarity",
    "front_image_url",
    "back_image_url",
    "updated_at"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^p[\\w]+-\\d{3}[a-z]?$"
    },
    "part": {
      "type": "string",
      "minLength": 1
    },
    "number": {
      "type": "string",
      "pattern": "^\\d{3}$"
    },
    "year": {
      "type": "integer",
      "minimum": 1900
    },
    "title_jp": {
      "type": "string",
      "minLength": 1
    },
    "title_en": {
      "type": "string"
    },
    "title_fr": {
      "type": "string"
    },
    "rarity": {
      "type": "string",
      "enum": [
        "standard",
        "prism",
        "special"
      ]
    },
    "front_image_url": {
      "type": "string",
      "format": "uri"
    },
    "back_image_url": {
      "type": "string",
      "format": "uri"
    },
    "prism_mask_url": {
      "type": "string",
      "format": "uri"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    }
  },
  "additionalProperties": false
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-007.json
{
  "id": "p1-007",
  "part": "1",
  "number": "007",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "冒険にいこう！",
  "title_en": "Let’s go on an adventure!",
  "title_fr": "Allons à l’aventure !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_1/part_1-007.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_1/part_1-007.webp",
  "updated_at": "2026-08-25T11:47:40.812Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-023.json
{
  "id": "p1-023",
  "part": "1",
  "number": "023",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "第23回天下一武道会",
  "title_en": "23rd World Martial Arts Tournament",
  "title_fr": "23ᵉ Tournoi d'arts martiaux",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_1/part_1-023.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_1/part_1-023.webp",
  "updated_at": "2026-08-25T11:47:40.816Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-048.json
{
  "id": "p2-048",
  "part": "2",
  "number": "048",
  "year": 1991,
  "rarity": "prism",
  "title_jp": "ギニュー特戦隊到着！",
  "title_en": "The Ginyu Force arrives!",
  "title_fr": "Le Commando Ginyu arrive !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards-api/assets/images/front/part_2/part_2-048.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards-api/assets/images/back/part_2/part_2-048.webp",
  "prism_mask_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards-api/assets/images/mask/part_2/part_2-048.webp",
  "updated_at": "2026-08-25T19:05:07.880Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-042.json
{
  "id": "p1-042",
  "part": "1",
  "number": "042",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "ディナータイム",
  "title_en": "Dinner time",
  "title_fr": "L’heure du dîner",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_1-042.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_1-042.webp",
  "updated_at": "2026-08-23T11:51:44.026Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-037.json
{
  "id": "p1-037",
  "part": "1",
  "number": "037",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "地球よ、オラに力を！",
  "title_en": "Earth, lend me your energy!",
  "title_fr": "Terre, prête-moi ton énergie !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_1/part_1-037.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_1/part_1-037.webp",
  "updated_at": "2026-08-25T11:47:40.820Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-049.json
{
  "id": "p2-049",
  "part": "2",
  "number": "049",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "大格闘！",
  "title_en": "A great battle!",
  "title_fr": "Un grand combat !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2/part_2-049.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2/part_2-049.webp",
  "updated_at": "2026-08-25T09:35:44.851Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p2-074.json
{
  "id": "p2-074",
  "part": "2",
  "number": "074",
  "year": 1991,
  "rarity": "standard",
  "title_jp": "ついに対決の時",
  "title_en": "At last, the time for the showdown",
  "title_fr": "Enfin, l’heure de l’affrontement",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_2-074.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_2-074.webp",
  "updated_at": "2026-08-17T17:05:29.401Z"
}

=== fchavonet/full_stack-db_visual_adventure_cards_api/api/v1/cards/p1-001.json
{
  "id": "p1-001",
  "part": "1",
  "number": "001",
  "year": 1991,
  "rarity": "prism",
  "title_jp": "宝ものはいただきだ！",
  "title_en": "I'll take that treasure!",
  "title_fr": "Je prends ce trésor !",
  "front_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/front/part_1/part_1-001.webp",
  "back_image_url": "https://fchavonet.github.io/full_stack-db_visual_adventure_cards_api/assets/images/back/part_1/part_1-001.webp",
  "updated_at": "2026-08-25T09:35:44.823Z"
}
